add init to normal container start

diff --git a/spodcast-init b/spodcast-init
--- a/spodcast-init
+++ b/spodcast-init
@@ -27,13 +27,26 @@ while getopts ":hl:" option; do
    esac
 done
 
+if [ -e "/data/cred.json" ]
+then
+  echo "Already initialized, exiting"
+  exit
+fi
 
 if [ ! -e $cred_file ]
 then
-  echo "Credential file not found at $cred_file"
-  exit 1
+  echo ${SPOTIFY_USER} ${SPOTIFY_PW} > ${cred_file}
 fi
 
 mkdir -p /data/output
-spodcast -c /data/spodcast.json --root-path /data/output --log-level info --credentials-location creds.json -l /data/login.txt
+
+counter=0
+until spodcast -c /data/spodcast.json --root-path /data/output --log-level info --credentials-location creds.json -l /data/login.txt
+do
+   sleep 1
+   [[ counter -eq ${TIMEOUT_RETRY_NUM} ]] && echo "Failed!" && exit 1
+   echo "Trying again. Try #${counter}"
+   ((counter++))
+done
+
 cp /data/spodcast-cred-*.json /data/cred.json
